[tool.poetry]
name = "street-fighter-ii-ai"
version = "0.1.0"
description = ""
authors = ["dthelegend <wampamba.daudi@gmail.com>"]
readme = "README.md"
packages = [{include = "street_fighter_ii_ai"}]

[tool.poetry.dependencies]
python = "^3.11"
gymnasium = "^0.28.1"
cmake = "^3.26.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
